# Analysis Example 1
# Checking for increase in Firefox Desktop MAU from Nov 30.
[analysis_profile]
name="Desktop MAU"

[analysis_profile.dataset]
metric_name="mau"
# this will have to specify the query template
table_name="active_user_aggregates"
app_name="Firefox Desktop"  # this is very specific
period_offset = 28
current_period= 1
baseline_period = 1
processing_period_offset = 1

[analysis_profile.percent_change]
contrib_to_overall_change_threshold_percent = 1
include_dimension_permutations = true
dimensions=[
    "region_name",
    "subregion_name",
    "country",
]
sort_by=[
    "change_distance",
    "contrib_to_overall_change",
    "percent_change",
    "change_in_proportion",
]

[notification]
[notification.report]
template = "report_version2.html.j2"

[notification.slack]
channel = "#overwatch-mvp"
message = "Firefox Desktop MAU"
