# Analysis Example 4
# Checking for drop in Fenix DAU mid March
# https://docs.google.com/document/d/1umr5P35s4WM2zULyfNoBH_QrGubT9r89QeIuhE14Lzg/edit#
[analysis_profile]
name="Fenix DAU"

[analysis_profile.dataset]
metric_name="dau"
# this will have to specify the query template
table_name="active_user_aggregates"
app_name="Fenix"  # this is very specific
period_offset = 7
current_period= 1
baseline_period = 1
processing_period_offset = 1

[analysis_profile.percent_change]
contrib_to_overall_change_threshold_percent = 1
include_dimension_permutations = true
dimensions=[
            "region_name",
            "subregion_name",
            "country",
]
sort_by=[
    "change_distance",
    "contrib_to_overall_change",
    "percent_change",
    "change_in_proportion",
]
results_rounding = 2
limit_results = 10

[notification]
[notification.report]
template = "report_version2.html.j2"

[notification.slack]
channel = "#overwatch-mvp"
message = "Fenix DAU"
