[analysis_profile]
name="New Profiles for iOS"

[analysis_profile.dataset]
metric_name="new_profiles"
table_name="active_user_aggregates"
app_name="Firefox iOS"
baseline_period = 1
current_period= 1
period_offset = 7
processing_period_offset = 1

[analysis_profile.percent_change]
overall_threshold_percent = 0
contrib_to_overall_change_threshold_percent = 0
include_dimension_permutations = true
dimensions=[
    "country",
    "os_version",
    "attribution_medium",
    "channel"
]
sort_by=[
    "contrib_to_overall_change",
    "percent_change",
    "diff",
]
results_rounding = 2
limit_results = 10

[notification]
[notification.report]
template = "report_version3.html.j2"

[notification.slack]
channel = "#overwatch-reports"
message = "New Profiles for iOS"
